### ISSUE TITLE
Error: Cannot clone object PredefinedWeightsInputToNode

### ISSUE THREAD

**Issue by Jingyan0520** [TUD-STKS/PyRCN#18]
Hi,

I have updated PyRCN to the latest version 0.0.12. And I can't use "clone" on the class "PredefinedWeightsInputToNode" any more. 
The following is the code and error message:

`base_input_to_node = PredefinedWeightsInputToNode(...)`
`input_to_node = clone(base_input_to_node)`

`RuntimeError: Cannot clone object PredefinedWeightsInputToNode(activation='identity', hidden_layer_size=1000,
                             input_scaling=0.4, predefined_input_weights=array([[-0.08102128, -0.6120667 ,  0.26820713, ....   ]], dtype=float32),
                             random_state=1), as the constructor either does not set or modifies parameter hidden_layer_size`

Thank you for your help!

**Comment by renierts** [comment]
Hi @Jingyan0520,
thank you for reporting the bug. I have fixed it and release it with v0.0.13 hopefully tonight. On the dev branch, it is already available for the case you want to clone the repository and install it via

python setup.py install

**Comment by Jingyan0520** [comment]
Ok! Thank you very much!

**Comment by renierts** [comment]
v0.0.13 with the bugfix is online. You can hopefully upgrade it. Can you please confirm wether it works and close the issue or notify me about further bugs?

**Comment by Jingyan0520** [comment]
Yes, it works well. Thank you!
