### ISSUE TITLE
Is there any good way to adjust the parameters？

### ISSUE THREAD

**Issue by imhithanks** [TUD-STKS/PyRCN#3]
PyRCN is really a great API . 
There are many parameters inside . Is there any good way to adjust the parameters ？
Thank you for your help.

**Comment by renierts** [comment]
Hi @imhithanks and thanks for your question.
Please have a look at our tutorials or referred publications.

This binder example might be a good start: https://mybinder.org/v2/gh/TUD-STKS/PyRCN/master?filepath=examples%2Fdigits.ipynb

**Comment by imhithanks** [comment]
Thank you for your guidance. 
But I can't find this reference PyRCN: Exploration and Application of ESNs. 
Could you please tell me where to download it ？

**Comment by renierts** [comment]
This paper is not yet published but under review. I will update the README with a download link for the PyRCN paper as soon as possible. For now, you can follow any of those publications to optimize an ESN for a given task: 

- Note Onset Detection using Echo State Networks: http://www.essv.de/pdf/2020_157_164.pdf
- Feature Engineering and Stacked ESNs for Musical Onset Detection: https://www.researchgate.net/publication/344597826_Feature_Engineering_and_Stacked_Echo_State_Networks_for_Musical_Onset_Detection
- Multiple-F0 Estimation using Echo State Networks: https://www.eurasip.org/Proceedings/Eusipco/Eusipco2020/pdfs/0000126.pdf

It always includes the following steps:
1. Optimize input scaling and spectral radius
2. Optimize leakage
3. Optimize bias
4. Increase reservoir size and introduce bi_directional reservoirs

**Comment by imhithanks** [comment]
@renierts  I see. Thank you very much！

**Comment by renierts** [comment]
You're welcome!
