### ISSUE TITLE
Some documentation spellings

### ISSUE THREAD

**Issue by nTrouvain** [TUD-STKS/PyRCN#47]
Hello,

We noticed that some of the code you produced seems greatly inspired by the tool we develop, called ReservoirPy.  In particular, your code for `mackey_glass` timeseries generation is identical to ours, and the last lines of your "Getting started" section in your documention are explicitely taken from the documentation of ReservoirPy (you forgot to remove the name of our package...).

We would really love to see more collaboration on the subject of Reservoir Computing software, and would be very happy to receive feedback from you about our tool, especially if you take some parts and improve them, for instance. However, could it be possible in this case to be at least cited in your code? As our tools seem to be focused towards the same objective, I think we would really greatly benefit from more communication and collaboration. Thank you in advance.

**Comment by renierts** [comment]
Hello,

thank you for pointing this out. In fact, I really like the implementation of ```mackey_glass``` and the documentation style. I have totally forgotten to add the citations in these parts. This is a no-go and it will never happen again. I promise you to give an extensive feedback to ReservoirPy in the next days.

This is something that should never ever have happened and I really regret it!

In the next days, I willl further update the documentation and mention this issue in the commits to keep you up-to-date!

**Comment by nTrouvain** [comment]
Hello,
Thank you for fixing this. The citation is perfectly fine. We just wanted to point out that Reservoir Computing softwares developpment  should be a collective work, as this is a truly missing part of ML softwares these days. We will also continue to dive into your tool, and give you feedback whenever it is possible.
