### ISSUE TITLE
ReservoirWeightGeneration_TIMIT notebook dependencies not available

### ISSUE THREAD

**Issue by alvin-garcia** [TUD-STKS/PyRCN#50]
Hello PyRCN Team,

I followed the basic tutorial and got it to work.

![Screen Shot 2022-08-15 at 10 48 07 AM](https://user-images.githubusercontent.com/33560765/184688130-c103c481-feef-4cf2-b83c-62f4b725f045.png)

I want to adapt the TIMIT notebook to my dataset since I'm doing classification over spectrogram images as shown below.

![image](https://user-images.githubusercontent.com/33560765/184688340-888449d0-48ae-4913-88a7-a0e31b294808.png)

Using a sliding window with 75% overlap, the inputs are `[samples*sliding windows, timestamps in window, frequency]`. You'll notice four "sub-bins" per dashed window in the predictions.

However, I can't seem to import the dependencies shown below.

![Screen Shot 2022-08-15 at 10 47 15 AM](https://user-images.githubusercontent.com/33560765/184687975-4a56a597-6fe9-4853-892f-8aeb5e853c46.png)

My versions are up to date

![Screen Shot 2022-08-15 at 10 53 34 AM](https://user-images.githubusercontent.com/33560765/184688967-754a83ab-2b4f-4f04-a2e8-f1871a69d02f.png)

Please update the dependencies. Thanks.

**Comment by renierts** [comment]
Dear @alvin-garcia,

thanks for bringing up this issue. In fact, I was already notified about this before. The ```SeqToSeqESNClassifier``` is no more required and now included in the ```ESNClassifier```. You can have a look on the updated version of the notebook in the dev-Branch. After releasing the next version of PyRCN, this will be available on the main branch.

**Comment by renierts** [comment]
Dear @alvin-garcia,

with the release of the new version of PyRCN, we updated everything. Can you please confirm whether this works now and close this issue if so?

**Comment by alvin-garcia** [comment]
Dear @renierts,

Thanks for looking into this issue. I need help getting the RCN code to run successfully. I noticed the TIMIT example was removed from the examples, so instead I will attach what I really want to train.
[rcn_spec.pdf](https://github.com/TUD-STKS/PyRCN/files/9425297/rcn_spec.pdf)

There's an issue in `~/.conda/envs/tf2-gpu/lib/python3.7/site-packages/pyrcn/echo_state_network/_esn.py`, with `ndim` on line 205. Wrapping the input using `np.asarray` created a new error. Not sure how to proceed?

![Screen Shot 2022-08-25 at 9 57 40 AM](https://user-images.githubusercontent.com/33560765/186684526-7bfc6eb0-9307-4462-ae35-ca8f8f9e2a41.png)

**Comment by renierts** [comment]
Hi @alvin-garcia,

thanks for the hint. I noticed from your appended example that you want to train the ESN with multiple spectrograms (each spectrogram is a sequence).
As shown in the documentation, this can be done by passing numpy arrays to the ESN.
I think, the solution to your problem is to change a few lines of code in cell 12 your jupyter notebook:

There, you have the following lines:

```
X_train = [x for x in x_train_arr]
y_train = [y for y in y_train_arr]
X_test = [x for x in x_val_arr]
y_test = [y for y in y_val_arr]
```

you should change these lines of code to the following:

```
X_train = np.empty(shape=(x_train_arr.shape[0], ), dtype=object)  # shape is the number of sequences/spectrograms
y_train = np.empty(shape=(y_train_arr.shape[0], ), dtype=object)  # shape is the number of sequences/spectrograms
X_test = np.empty(shape=(x_test_arr.shape[0], ), dtype=object)  # shape is the number of sequences/spectrograms
y_test = np.empty(shape=(y_test_arr.shape[0], ), dtype=object)  # shape is the number of sequences/spectrograms
for k, (x, y) in enumerate(zip(x_train_arr, y_train_arr)):
    X_train[k] = x  # x has the shape (n_samples, n_features)
    y_train[k] = y
for k, (x, y) in enumerate(zip(x_test_arr, y_test_arr)):
    X_test[k] = x  # x has the shape (n_samples, n_features)
    y_test[k] = y
```
This creates a numpy array of dtype object (similar as a list). PyRCN will then iterate across each element in this numpy array.

**Comment by alvin-garcia** [comment]
Ah interesting solution, yes that worked. Thanks!

However, now I'm getting another error, which I'm trying to figure out right now.

I understand the k_in parameter, not sure why there would be a divide by zero in this part of the code?

```
Fitting 5 folds for each of 200 candidates, totalling 1000 fits
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 128 concurrent workers.
[Parallel(n_jobs=-1)]: Done 194 tasks      | elapsed:    5.8s
[Parallel(n_jobs=-1)]: Done 544 tasks      | elapsed:    8.0s
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed:   11.0s finished
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-13-0267e97c79d3> in <module>
     35 base_esn = ESNClassifier(**initially_fixed_params)
     36 
---> 37 sequential_search = SequentialSearchCV(base_esn, searches=searches).fit(np.asarray(X_train[:10]), np.asarray(y_train[:10]))
     38 dump(sequential_search, "first_try.joblib")  # TODO: undo the "large" settings!

~/.conda/envs/tf2-gpu/lib/python3.7/site-packages/pyrcn/model_selection/_search.py in fit(self, X, y, groups, **fit_params)
    190                 self.all_multimetric_[name] = result.multimetric_
    191                 self.estimator = result.best_estimator_
--> 192         self._run_search(evaluate_candidates)
    193         return self
    194 

~/.conda/envs/tf2-gpu/lib/python3.7/site-packages/pyrcn/model_selection/_search.py in _run_search(self, evaluate_candidates)
    136         evaluate_candidates: Callable
    137         """
--> 138         evaluate_candidates(self.searches)
    139 
    140     def fit(self, X: np.ndarray, y: Optional[np.ndarray], *,

~/.conda/envs/tf2-gpu/lib/python3.7/site-packages/pyrcn/model_selection/_search.py in evaluate_candidates(searches)
    175                     result = search(
    176                         self.estimator, params, refit=True, **kwargs[0])\
--> 177                         .fit(X, y)
    178                 else:
    179                     result = search(

~/.conda/envs/tf2-gpu/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

~/.conda/envs/tf2-gpu/lib/python3.7/site-packages/sklearn/model_selection/_search.py in fit(self, X, y, groups, **fit_params)
    763             refit_start_time = time.time()
    764             if y is not None:
--> 765                 self.best_estimator_.fit(X, y, **fit_params)
    766             else:
    767                 self.best_estimator_.fit(X, **fit_params)

~/.conda/envs/tf2-gpu/lib/python3.7/site-packages/pyrcn/echo_state_network/_esn.py in fit(self, X, y, n_jobs, transformer_weights)
    738             self._check_if_sequence(X, y)
    739         if self.requires_sequence:
--> 740             self._input_to_node.fit(X[0])
    741             self._node_to_node.fit(self._input_to_node.transform(X[0]))
    742             self._check_if_sequence_to_value(X, y)

~/.conda/envs/tf2-gpu/lib/python3.7/site-packages/pyrcn/base/blocks/_input_to_node.py in fit(self, X, y)
    132                 n_features_in=self.n_features_in_,
    133                 hidden_layer_size=int(self.hidden_layer_size), fan_in=fan_in,
--> 134                 random_state=self._random_state)
    135         if self.predefined_bias_weights is not None:
    136             assert self.predefined_bias_weights.shape == (

~/.conda/envs/tf2-gpu/lib/python3.7/site-packages/pyrcn/base/_base.py in _uniform_random_input_weights(n_features_in, hidden_layer_size, fan_in, random_state)
    192     input_weights = _uniform_random_weights(
    193         n_inputs=n_features_in, n_outputs=hidden_layer_size, k_in=fan_in,
--> 194         random_state=random_state)
    195     return input_weights
    196 

~/.conda/envs/tf2-gpu/lib/python3.7/site-packages/pyrcn/base/_base.py in _uniform_random_weights(n_inputs, n_outputs, k_in, random_state)
    164 
    165     if k_in < n_outputs:
--> 166         return _make_sparse(k_in, dense_weights, random_state)
    167     else:
    168         return dense_weights

~/.conda/envs/tf2-gpu/lib/python3.7/site-packages/pyrcn/base/_base.py in _make_sparse(k_in, dense_weights, random_state)
     94     nr_entries = int(n_inputs * k_in)
     95     indices = np.zeros(shape=nr_entries, dtype=int)
---> 96     indptr = np.arange(start=0, stop=(n_inputs + 1) * k_in, step=k_in)
     97     dense_weights = dense_weights.flatten()[:nr_entries]
     98 

ZeroDivisionError: division by zero

```

**Comment by renierts** [comment]
Great that it works.

Sure, I will not close the issue before you notify me that everything works. You can close it by yourself as well, if you want.
