### ISSUE TITLE
About supporting Liquid State Machine

### ISSUE THREAD

**Issue by AXYZdong** [TUD-STKS/PyRCN#55]
When will this repo support Liquid State Machines (LSMs)?

**Comment by renierts** [comment]
Hello,

LSMs are still under development, since these require important code refactorizations. If you are interested in Spiking Neural Networks in general, we would still be glad to see how we can support you. Therefore, please directly send me an email.

**Comment by AXYZdong** [comment]
> Hello,
> 
> LSMs are still under development, since these require important code refactorizations. If you are interested in Spiking Neural Networks in general, we would still be glad to see how we can support you. Therefore, please directly send me an email.

Thank you very much, I will keep an eye on this repo.
